# Unified Construction Management API
name = "construction-management-unified"
main = "src/index.js"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

# Default environment (development)
[vars]
ENVIRONMENT = "development"
API_VERSION = "2.0.0"
CORS_ORIGIN = "*"
JWT_SECRET = "unified-dev-jwt-secret-2025"
ENABLE_DEBUG = "true"

# Supabase Configuration
SUPABASE_URL = "https://pbecqosbkuyypsgwxnmq.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZWNxb3Nia3V5eXBzZ3d4bm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDgyOTcsImV4cCI6MjA3MDIyNDI5N30.RxgJZpII8Fm1ym6UtMEdmw87DExR1MxtJXISag9vszQ"

# Emergency Access
ENABLE_EMERGENCY_LOGIN = "true"
EMERGENCY_ADMIN_PHONE = "0900000000"

# KV Namespaces
[[kv_namespaces]]
binding = "SESSIONS"
id = "3d3356dca3684619bea5750829dbcaa5"

[[kv_namespaces]]
binding = "USERS"
id = "55484742a0dd4410b548aaa506c8c0bc"

[[kv_namespaces]]
binding = "SYNC_STATE"
id = "4f55c6c04ae74847a9339c0bf2584c4a"

# R2 Bucket for file uploads
[[r2_buckets]]
binding = "CONSTRUCTION_PHOTOS"
bucket_name = "construction-photos"

# D1 Databases
[[d1_databases]]
binding = "DB_CRM"
database_name = "fx-crm-database"
database_id = "332221d8-61cb-4084-88dc-394e208ae8b4"

[[d1_databases]]
binding = "DB_ENGINEERING"
database_name = "engineering-management"
database_id = "21fce5cd-8364-4dc2-be7f-6d68cbd6fca9"

# ========================================
# Development Environment
# ========================================
[env.development]
name = "construction-management-unified-dev"

[env.development.vars]
ENVIRONMENT = "development"
API_VERSION = "2.0.0"
API_BASE_URL = "https://construction-management-unified-dev.lai-jameslai.workers.dev"
FRONTEND_BASE_URL = "https://cm-dev.pages.dev"
CORS_ORIGIN = "*"
ENABLE_DEBUG = "true"
ENABLE_EMERGENCY_LOGIN = "true"
JWT_SECRET = "unified-dev-jwt-secret-2025"
SUPABASE_URL = "https://pbecqosbkuyypsgwxnmq.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZWNxb3Nia3V5eXBzZ3d4bm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDgyOTcsImV4cCI6MjA3MDIyNDI5N30.RxgJZpII8Fm1ym6UtMEdmw87DExR1MxtJXISag9vszQ"
EMERGENCY_ADMIN_PHONE = "0900000000"

# KV Namespaces
[[env.development.kv_namespaces]]
binding = "SESSIONS"
id = "3d3356dca3684619bea5750829dbcaa5"

[[env.development.kv_namespaces]]
binding = "USERS"
id = "55484742a0dd4410b548aaa506c8c0bc"

[[env.development.kv_namespaces]]
binding = "SYNC_STATE"
id = "4f55c6c04ae74847a9339c0bf2584c4a"

# R2 Bucket
[[env.development.r2_buckets]]
binding = "CONSTRUCTION_PHOTOS"
bucket_name = "construction-photos"

# D1 Databases
[[env.development.d1_databases]]
binding = "DB_CRM"
database_name = "fx-crm-database"
database_id = "332221d8-61cb-4084-88dc-394e208ae8b4"

[[env.development.d1_databases]]
binding = "DB_ENGINEERING"
database_name = "engineering-management"
database_id = "21fce5cd-8364-4dc2-be7f-6d68cbd6fca9"

# ========================================
# Production Environment
# ========================================
[env.production]
name = "construction-management-unified"

[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "2.0.0"
API_BASE_URL = "https://construction-management-unified.lai-jameslai.workers.dev"
FRONTEND_BASE_URL = "https://cm-prod.pages.dev"
CORS_ORIGIN = "https://cm-prod.pages.dev"
ENABLE_DEBUG = "false"
ENABLE_EMERGENCY_LOGIN = "false"
JWT_SECRET = "unified-prod-jwt-secret-2025"
SUPABASE_URL = "https://pbecqosbkuyypsgwxnmq.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZWNxb3Nia3V5eXBzZ3d4bm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDgyOTcsImV4cCI6MjA3MDIyNDI5N30.RxgJZpII8Fm1ym6UtMEdmw87DExR1MxtJXISag9vszQ"
EMERGENCY_ADMIN_PHONE = ""

# KV Namespaces
[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "3d3356dca3684619bea5750829dbcaa5"

[[env.production.kv_namespaces]]
binding = "USERS"
id = "55484742a0dd4410b548aaa506c8c0bc"

[[env.production.kv_namespaces]]
binding = "SYNC_STATE"
id = "4f55c6c04ae74847a9339c0bf2584c4a"

# R2 Bucket
[[env.production.r2_buckets]]
binding = "CONSTRUCTION_PHOTOS"
bucket_name = "construction-photos"

# D1 Databases
[[env.production.d1_databases]]
binding = "DB_CRM"
database_name = "fx-crm-database"
database_id = "332221d8-61cb-4084-88dc-394e208ae8b4"

[[env.production.d1_databases]]
binding = "DB_ENGINEERING"
database_name = "engineering-management"
database_id = "21fce5cd-8364-4dc2-be7f-6d68cbd6fca9"