name = "construction-management-frontend"
pages_build_output_dir = "../frontend"
compatibility_date = "2024-11-06"

# Environment variables for Pages
[vars]
API_URL = "https://construction-management-api.lai-jameslai.workers.dev"