name = "construction-management-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
node_compat = true

# Production environment
[env.production]
name = "construction-management-api-prod"

# D1 Databases - Production
[[env.production.d1_databases]]
binding = "DB_CRM"
database_name = "fx-crm-database"
database_id = "332221d8-61cb-4084-88dc-394e208ae8b4"

[[env.production.d1_databases]]
binding = "DB_ENGINEERING"
database_name = "engineering-management"
database_id = "21fce5cd-8364-4dc2-be7f-6d68cbd6fca9"

# KV Namespaces - Production
[[env.production.kv_namespaces]]
binding = "SESSION_STORE"
id = "YOUR_PRODUCTION_SESSION_STORE_ID"

[[env.production.kv_namespaces]]
binding = "SYNC_STATE"
id = "YOUR_PRODUCTION_SYNC_STATE_ID"

# R2 Buckets - Production
[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "construction-photos-prod"

# Environment Variables - Production
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "v1"
CORS_ORIGIN = "https://your-domain.com"
LOG_LEVEL = "info"
RATE_LIMIT_PER_MINUTE = "100"
SESSION_DURATION_HOURS = "24"
MAX_FILE_SIZE_MB = "10"

# Custom domains (optional)
# [env.production.routes]
# pattern = "api.your-domain.com/*"
# custom_domain = true

# Analytics (optional)
# [env.production.analytics_engine_datasets]
# binding = "ANALYTICS"