name = "construction-api-new"
main = "src/api-final.js"
compatibility_date = "2024-11-06"

[vars]
ENVIRONMENT = "production"
DEV_TOKEN = "dev-token-for-testing"

# KV Namespaces
[[kv_namespaces]]
binding = "SESSIONS"
id = "3d3356dca3684619bea5750829dbcaa5"

[[kv_namespaces]]
binding = "USERS"
id = "55484742a0dd4410b548aaa506c8c0bc"

[[kv_namespaces]]
binding = "FILES_KV"
id = "1e62bab6fb30404e9b753dd0b1f1ee6a"

[[kv_namespaces]]
binding = "SESSION_STORE"
id = "8c8b7ae9df6b43f18a457a0cea0affc2"

[[kv_namespaces]]
binding = "SYNC_STATE"
id = "4f55c6c04ae74847a9339c0bf2584c4a"

# R2 Bucket
[[r2_buckets]]
binding = "CONSTRUCTION_PHOTOS"
bucket_name = "construction-photos"

# D1 Databases
[[d1_databases]]
binding = "DB_CRM"
database_name = "fx-crm-database"
database_id = "332221d8-61cb-4084-88dc-394e208ae8b4"

[[d1_databases]]
binding = "DB_ENGINEERING"
database_name = "engineering-management"
database_id = "21fce5cd-8364-4dc2-be7f-6d68cbd6fca9"