name: Deploy Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd workers
          npm ci
      
      - name: Deploy API to Cloudflare Workers
        run: |
          cd workers
          npx wrangler deploy --config wrangler-production.toml
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_PRODUCTION }}
      
      - name: Deploy Frontend to Cloudflare Pages
        run: |
          cd workers
          npx wrangler pages deploy ../frontend \
            --project-name construction-management-frontend-prod \
            --branch production \
            --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_PRODUCTION }}