name: Deploy API to Development

on:
  push:
    branches: [develop]
    paths:
      - 'workers/src/**'
      - 'workers/wrangler.dev.toml'
      - '.github/workflows/deploy-api-dev.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy API Development
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'workers/package-lock.json'

      - name: Install dependencies
        working-directory: ./workers
        run: npm ci

      - name: Deploy to Cloudflare Workers
        working-directory: ./workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_DEVELOPMENT }}
        run: npx wrangler deploy --config wrangler.dev.toml

      - name: Health Check
        run: |
          sleep 5
          curl -f https://construction-management-api-dev.lai-jameslai.workers.dev/health
          echo "✅ Development API deployment successful!"

      - name: Notify Deployment
        if: success()
        run: |
          echo "🚀 API Development deployment completed successfully"
          echo "📍 URL: https://construction-management-api-dev.lai-jameslai.workers.dev"